// Generated by CoffeeScript 1.7.1
(function() {
  var addScript;

  addScript = function(src, script, onload) {
    var scriptElement;
    scriptElement = document.createElement('script');
    if (src != null) {
      scriptElement.src = src;
    } else {
      scriptElement.innerText = script;
    }
    if (onload != null) {
      scriptElement.addEventListener('load', function(e) {
        onload(e);
        return document.body.removeChild(scriptElement);
      });
    }
    return document.body.appendChild(scriptElement);
  };

  addScript('//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js', null, function() {
    return addScript(chrome.extension.getURL('js/inject.js'), null, function() {
      return addScript(null, "chatfree.auth('" + chrome.runtime.id + "')");
    });
  });

}).call(this);
