// Generated by CoffeeScript 1.7.1
(function() {
  var addScript;

  addScript = function(src, onload) {
    var scriptElement;
    scriptElement = window.document.createElement('script');
    scriptElement.src = src;
    scriptElement.onload = onload;
    window.document.body.appendChild(scriptElement);
  };

  addScript('//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js', function() {
    return addScript(window.chrome.extension.getURL('js/inject.js'));
  });

}).call(this);
